### ISSUE TITLE
Absolute path to scratch subdirectories not correctly built

### ISSUE THREAD

**Issue by rediet-orange** [DvdMgr/sem#42]
Hi Davide,

We had difficulties using SEM with scripts lying in a subdirectory of scratch.

Tracing back to runner.py, during init [L98](https://github.com/signetlabdei/sem/blob/master/sem/runner.py#L98), I noticed that the reconstruction of the absolute path ignored potential subdirectories within scratch (i.e. for a script in `scratch\subdir\script`, `self.script_executable` is rebuilt as `\[ns_path]\build\optimized\scratch\script` for optimized mode).
Btw, we tried providing `subdir\script` but it failed to find it during the preceding search.

It would be great if this gets fixed (we found a quick-and-dirty workaround of hard-coding the subdir in the source code...).

BR,

Rediet

**Comment by DvdMgr** [comment]
Hi Rediet, thanks for pointing this out! Should be fixed in commit c540328a07bc4d0dda95e7afa71bab9602ef3850 on develop, and in commit b704be8c82fee6411d5aba98d24079dcb58d1fd9 on master - just specify the name of the scratch subfolder for the `script` argument when you create the campaign. I plan to make a new SEM release on PyPI (for installation with the `pip install sem` command) before WNS3, but I can also push this change right now in a minor release if it makes it easier for you (this really depends on how you installed SEM - if you want, you can install the develop "release" by issuing `pip install https://github.com/signetlabdei/sem/archive/develop.zip`).

**Comment by rediet-orange** [comment]
Hi Davide,

Thanks for the quick fix. No, don't bother building another release. I have a solution at hand (plus the changes of the latest commit) so it'll do.

Rediet
